export enum BPRoute {
  Root = '/',
  Auth = 'auth',
  Register = 'register',
  Content = 'content',
  Profile = 'profile',
  Blogs = 'blogs',
  BlogCreate = 'create-blog',
  BlogEdit = 'edit',
  Posts = 'posts',
  PostEdit = 'edit',
  PostCreate = 'create-post',
  NotFound = '404',
  Forbidden = '403',
}
