###
POST http://localhost:8080/api/v/n/1/register
Content-Type: application/json

{
  "login": "test",
  "firstName": "Test name",
  "password": "1234",
  "email": "my-email@lol.com"
}

###
POST http://localhost:8080/api/v/n/1/auth
Content-Type: application/json

{
  "login": "test",
  "password": "1234"
}

###
GET http://localhost:8080/api/v/n/1/users/test
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0Iiwicm9sZXMiOlsiVVNFUiJdLCJsb2dpbiI6InRlc3QiLCJleHAiOjE2NjUyNDczMjgsImlhdCI6MTY2NTIyOTMyOH0.7xwsZFNcHIsOfIE_fzMEKNyl3oXqFyNCQPv14BEs1srNZmRu4bmatUSS3gLArtN0EWuFqCfV3Qd2MF3jeIHj3Q

###
POST http://localhost:8080/api/v/n/1/users/search
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0Iiwicm9sZXMiOlsiVVNFUiJdLCJsb2dpbiI6InRlc3QiLCJleHAiOjE2NjUyNTY1ODAsImlhdCI6MTY2NTIzODU4MH0.ypJYKrWJWzJhYKYOYeMW330enC6AMzNm9lsc2wzsXEb3ruGR9yiH6C4-T8Vy1BGcOB3gUBjwtj_tLRzpI4DADQ
Content-Type: application/json

{
 "login": "test"
}

###
GET http://localhost:8080/api/v/n/1/register/test/dsf
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0Iiwicm9sZXMiOlsiVVNFUiJdLCJsb2dpbiI6InRlc3QiLCJleHAiOjE2NjUyNDczMjgsImlhdCI6MTY2NTIyOTMyOH0.7xwsZFNcHIsOfIE_fzMEKNyl3oXqFyNCQPv14BEs1srNZmRu4bmatUSS3gLArtN0EWuFqCfV3Qd2MF3jeIHj3Q

###
GET http://localhost:8080/api/v/n/1/admin/health